### ISSUE TITLE
Album or Track artwork in the player and Building a persistent player

### ISSUE THREAD

**Issue by ghost** [zirafa/pushtape-player.js#3]
Hi, Im developing a theme for Pushtape called Musica and Im interested in building a method to add track artwork to the player. Is this something that has been considered? Im also interested in expanding the player with dynamic playlists and a persistent player that follows you through the site. Has anyone else considered this or done any development on anything similar?

I dont want to reinvent the wheel unnecessarily.

thank you for your great work!

**Comment by zirafa** [comment]
Hi, the features you are looking for are somewhat beyond the scope of this JS script because they are site-dependent. However the autoscan feature makes building a persistent player very easy as it automatically updates the player's playlist whenever the underlying DOM changes. Check out http://github.com/zirafa/pushtape-cassette for an example of this persistent player navigation in action, as well as a method of connecting artwork to playlists. A while back I experimented with trying to [read ID3 tags directly](https://github.com/aadsm/jsmediatags), but it was somewhat kludgy so instead went with a simpler implementation via cassette.json.
